### PR TITLE
Lokiblocks integration

### PR DESCRIPTION
**Pull request by kylezs**
Integrates available service node information into the wallet. The "Service Node" tab is now split into 3. "My stakes" "Staking" and "Registration". The "Staking" tab now has a list of available service nodes that a user can stake to, with a summary of that node, and on click of "STAKE" auto-fills the form fields. The service node details page now links to the contributor's lokisn page when clicked on.

### CODE REVIEW

**Review by Mikunj — APPROVED** [review]
Looks good 👍

**Comment by KeeJef** [comment]
screenshots of this?

**Comment by kylezs** [comment]
Screen Shot 2020-09-08 at 3 25 26 pm
Screen Shot 2020-09-08 at 3 27 03 pm
@KeeJef here's a couple. Detail page is the same, just button changes between "Unlock" and "Stake" at the top depending on which it is

**Comment by KeeJef** [comment]
So when you press stake, next to the Service Nodes available, does it just fill in the SN key and the max amount?

**Comment by kylezs** [comment]
It fills the SN key and the min amount and snaps to the top (in case you are scrolled down where you can't see the fields). It also shows a green snackbar saying `Service node key and min amount filled`, so the user knows what's happening.

**Comment by KeeJef** [comment]
LGTM

**Pull request merged**
